### PR TITLE
Small improvments

### PR DESCRIPTION
**Pull request by adammockor**
Hello,

this PR improves few things. Please let me know, if it's ok with you.

Changes:  
* overlay will close on escape
* ability to override default styles of overlay

### CODE REVIEW

**Comment by Kikobeats** [comment]
Looks good!

How do you test it? could be nice provide a way to easily show how it looks.

Screens are also welcome

**Comment by adammockor** [comment]
I ain't change default visual, so screen is same as yours.

I just added ability to pass `{ styles }` object in `data` to overide default `styles` on message.

Also I added Esc key handler, which remove message from screen.

**Comment by Kikobeats** [comment]
go ahead 👍

**Comment by adammockor** [comment]
It would be great, if you can release new version, so I can pick it up. Thank you.

**Comment by Kikobeats** [comment]
Sorry for the delay, I bumped a new version right now 👍

**Pull request merged**
